### ISSUE TITLE
[Bug]: Flagrum having a fatal error whenever I try to apply or change mods 

### ISSUE THREAD

**Issue by light471** [Kizari/Flagrum#150]
### Operating System

Windows 10 64-Bit

### Game Version

Latest Steam Release

### Version

Flagrum v1.5.12

### Description of the bug

After updating to the latest version, i decided to try and set up my mods again, but I've been met with "fatal error has occurred" constantly. I regenerated my index files as well as reset/clean a couple of times along with freshly reinstalling flagrum yet it didn't help which is weird considering before updating it worked fine. 
What i think is causing the issue is that i had to manually reinstall flagrum 1.4 because it didn't open and i think that's part of the problem. 
i also reinstalled the game without any mods and it's still continuing. 

### Steps to reproduce the bug

1. open flagrum and apply a certain mod (always happens with Moogle Chocobo Carnival) 
2. wait a few seconds until it gives an error

### Crash logs

[2024-04-26_01-52-18-2301_crash_232129053.txt](https://github.com/Kizari/Flagrum/files/15125952/2024-04-26_01-52-18-2301_crash_232129053.txt)
[2024-04-26_01-54-56-8436_crash_255777633.txt](https://github.com/Kizari/Flagrum/files/15125953/2024-04-26_01-54-56-8436_crash_255777633.txt)
[2024-04-26_02-03-56-4636_crash_297767199.txt](https://github.com/Kizari/Flagrum/files/15126000/2024-04-26_02-03-56-4636_crash_297767199.txt)

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Kizari** [comment]
This is quite a strange one. The crash is occurring because your file index is somehow causing two of the same file hash to be loaded into memory. Since you already tried reinstalling and regenerating the file index, I can only assume the issue is that there is some file in your game data directory that most of us don't have. Why this is even more strange is that Flagrum discards entries with the same URI to prevent this exact issue, so it seems like whatever file is causing this has a URI that is different but produces the same hash.

Unfortunately the crash log doesn't specify which file is causing the issue. Is it possible you've placed something in the game data folder that wasn't there originally? If not, the only other thing I can think of is that maybe one of the game files has become corrupted somehow. I've just tried reindexing my files in the same version of Flagrum again and I didn't run into the bug. I can't promise with 100% certainty that reinstalling the game will resolve the issue, but it seems like the next logical step if there aren't any unexpected files in the game data directory to remove.

**Comment by light471** [comment]
a while back i moved a few exe's such as the ansel unblocker but iirc i put the original one back, i'll try a clean install of the game to see if the issue continues

**Comment by light471** [comment]
Good news and bad news, i moved it to a different drive after a frash install and was able to install and uninstall the mods i couldn't before but the issue still sometimes persists with certain mods which forces me to try again and the crash log is the same.

**Comment by light471** [comment]
well at this point i tried everything, even as far as reinstalling the game multiple times while also having the 4k resolution dlc on/off (didn't know if it'd make a difference but decided to try it). it's still the same error even though my game is installed in a new directory, so there's no way there are other files there. im confused as to what can be causing the issue.

**Comment by light471** [comment]
Not really, it's a clean install so that's why it's confusing

**Comment by Kizari** [comment]
When you uninstalled, did you delete the FFXV folder before reinstalling? Steam doesn't remove any non-original files when uninstalling games, so if you did have any, they may still be there.

**Comment by light471** [comment]
I'm not entirely sure, where is it located? I'll try to manually delete it and see if it causes any further issues

**Comment by Kizari** [comment]
![image](https://github.com/Kizari/Flagrum/assets/25322543/c95e43cb-75b2-473f-b8f7-ec08159cf141)

Default location is here, but may vary if you set your Steam Library up elsewhere. You'd want to delete the entire "Final Fantasy XV" folder **after** uninstalling, but before reinstalling.

**Comment by Kizari** [comment]
The issue #152 provided some more insight on this issue. This should be fixed in Flagrum 1.5.13 when it releases soon.

**Comment by light471** [comment]
I'm still confused as I deleted the entire game, yet it's still the same error, the only thing I could think of is if I'd manually replace the file to see if it'll solve it. But the thing is, I don't know exactly which file it is, and i'm not even sure if it'll help. But thanks for trying to help me with the issue I appreciate it.
