### ISSUE TITLE
[Bug]:Error Encountered when converting HEB to TGA

### ISSUE THREAD

**Issue by katekittaly** [Kizari/Flagrum#152]
### Operating System

Windows 10 64-Bit

### Game Version

Latest Steam Release

### Version

Flagrum v1.5.12

### Description of the bug

Flagrum encounters a fatal error when trying to convert all HEB to tga in game view at data folder level. You had fixed this issue at one point, but I don't know whether you included it in the latest release. Or perhaps this is a different issue.

### Steps to reproduce the bug

1. Go to asset explorer, game view
2. Convert in folder, HEB to tga.
3. Make a folder named HEB on desktop to export to. 

### Screenshots

[2024-05-06_02-02-37-2767_crash_1512598670.txt](https://github.com/Kizari/Flagrum/files/15224715/2024-05-06_02-02-37-2767_crash_1512598670.txt)
[2024-05-06_02-01-25-9673_crash_51721974.txt](https://github.com/Kizari/Flagrum/files/15224716/2024-05-06_02-01-25-9673_crash_51721974.txt)

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Kizari** [comment]
Fixed in 1.5.13.

**Comment by Rinual** [comment]
in case its relevant, issue persists even when exporting as .heb, 
[2024-05-22_10-03-47-1311_crash_1115549548.txt](https://github.com/Kizari/Flagrum/files/15410554/2024-05-22_10-03-47-1311_crash_1115549548.txt)

and on debug build, no exporting of .heb, in any format, works. no crash, no export, just finishes instantly.

**Comment by Rinual** [comment]
ok, the debug issue is that the game already has them unpacked on debug, unlike release, so ignore that

**Comment by Kizari** [comment]
The heightmaps being messed up is expected just FYI. The format they use can't really be exported to anything usable so I just let it use the default format and so it looks like that. The terrain importer still works though so it's not important.
