### ISSUE TITLE
Flagrum crashes when attempting to apply edits to the 4K pack DLC when the DLC is not present

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#43]
As stated in the title.

### Workaround

You can get around this by clicking on the mod card for the affected mod and deleting any files under earcs that target the 4K pack. These are any earcs with `/highimages/` in the path, or that end in `_$h2.earc`. To do this, click the arrow next to the earc to expand it, then click the trashcan icon next to each file inside it. Once this is done, click the Save button and it should build and apply the mod successfully.

This issue is planned to be fixed in the next patch.

### Developer Notes

The issue is caused by a crash that occurs when trying to access the earc as it does not exist on disk. This issue was fixed in the past, but appears to have regressed in Flagrum 1.4+ due to changes in the mod builder.

Two different crash logs were reported potentially associated with this issue, although some non-4K earcs were missing for this user as well, so keep this in mind when looking at them.

[crash.txt](https://github.com/Kizari/Flagrum/files/10881392/crash.26.txt)
[crash1.txt](https://github.com/Kizari/Flagrum/files/10881394/crash1.1.txt)

If the 4K pack is installed, this can be tested by renaming or moving one or more of the earcs the mod targets before attempting to enable the mod.

**Comment by Kizari** [comment]
This has been fixed in Flagrum 1.4.5.

**Comment by Rinual** [comment]
The given key was not present in the dictionary.

Flagrum will still crash when attempting to install a mod targeting .htpk files

**Comment by Rinual** [comment]
Seems like this problem comes from mods exported prior to the patch fixing the issue. Mod authors will need to update their listings by reexporting as an fmod for the issue to be resolved. 

Marking this as closed

**Comment by Rinual** [comment]
though.... i just tried Elisa's neck seam fix for ignis that has 4k textures and is old... and it installed fine 
so i actually have no idea whats going on

**Comment by Rinual** [comment]
re-opening this in case it does want to get addressed, now knowing that some legacy mods targeting the 4k pack will install, while others wont, with no pattern to what would cause the issues.

**Comment by Kizari** [comment]
Do we have any examples of mods that still trigger this issue?

**Comment by Rinual** [comment]
https://modworkshop.net/mod/37901
https://modworkshop.net/mod/37675

It is worth noting no mod remains on modworkshop that would benefit from this fix. Most of the mods with issues were intentionally updated to circumvent the issue, leaving only a few. Both of  of the mods above are made by modders which are still active, however since those mods have no benefit if fixed for 2k, it is unlikely to be a good use of the developers time. 

Compatibility with nexus texture replacements havent been checked, however it would be of limited benefit

**Comment by Kizari** [comment]
> It is worth noting no mod remains on modworkshop that would benefit from this fix

Ahh right, I wasn't aware they had all been addressed. In that case, will close this since it's no longer affecting anyone, nor is it affecting newly created mods. This issue can be referred to in future if the problem returns.
